### ISSUE TITLE
[BUG] Pickup point selection is not remembered fully on the page reload

### ISSUE THREAD

**Issue by YachYaroslav** [postnl/postnl-magento2#388]
**To Reproduce**
1. Go to native Magento checkout.
2. Fill the address of the Netherlands (e.g. Street Address - Weena XXXX, City - Rotterdam, Zip/Postal Code - 3013AL).
3. Click on 'PostNL' shipping method and select one of Pickup points.
4. Refresh the checkout page (F5).
6. Scroll down to 'PostNL' shipping method.

**Expected result**
'PostNL' shipping method is selected with 'Pickup' tab being active + previously selected Pickup point is remembered and selected.

**Actual result**
'PostNL' shipping method is selected, but **'Pickup' tab is not active** on the first try (secondly, etc. it's active). When I select 'Pickup' (or if it's selected by the PostNL module), I see a row of the selected pickup marked as active, but **the radio input inside the row is not checked itself**.

**Workaround**
None

**Screenshots**

Before reload:

![before-reload](https://github.com/user-attachments/assets/3a007fc5-4e0a-43e2-95c2-d63de7dc4250)

After reload:

![after-reload](https://github.com/user-attachments/assets/8f0133c0-2bc9-462a-8889-a7d059526751)

After reload + click "Next":

![after-reload-2](https://github.com/user-attachments/assets/92a76ab3-a2af-41cb-a6ac-bb9f6a500f1e)

- Magento version (pure with only tig/postnl-magento2): 2.4.6
- PHP version: 8.1.3
- TIG PostNL version: 1.15.2

---

Also the same issue is reproducible on a highly customized Magento (with Swissup_Firecheckout and many custom modules):

- Magento version: 2.4.3-p3
- PHP version: 7.4.28
- TIG PostNL version: 1.15.2

Magento version 2.4.3-p3 with Swissup_Firecheckout (the same bug):

![screenshot-from-another-version](https://github.com/user-attachments/assets/82957da6-068d-4ef0-90b8-965e520399ac)

**Comment by JorisPostNL** [comment]
Hi @YachYaroslav, thank you for reporting this issue.

Unfortunately the issue you mention is caused by the way the Magento2 framework itselfs works, and not by our plug-in. We have investigated this issue in the past and came to the conclusion we could not fix this issue without working on Magento2 itself rather than our plug-in. This means that unfortunately there is nothing we can do about this problem at this moment.

Note: since all three issues you posted concern the same root cause I will copy and paste this answer in all three tickets, so it's clear for other visitors what the outcome of your report was.

Kind regards
Joris - PostNL
