### ISSUE TITLE
[BUG] Not remembered frontend delivery and stated delivery fees after reloading the checkout page

### ISSUE THREAD

**Issue by YachYaroslav** [postnl/postnl-magento2#390]
**To Reproduce**
1. Go to 'Admin' -> 'Stores' -> 'Configuration' -> 'Sales' -> 'PostNL'
2. In the 'Delivery' section activate 'Today Delivery', 'Evening Delivery' and 'Delivery to stated address only'
3. Save config and clear the caches.
4. Go to frontend checkout page.
5. Fill the address of the Netherlands (e.g. Street Address - Weena XXXX, City - Rotterdam, Zip/Postal Code - 3013AL).
6. Click on 'PostNL' shipping method and select either 'Fast Delivery' or 'Evening Delivery' (one of deliveries with an additional fee).
7. Check extra service 'Do not deliver to neighbours'.
8. Refresh the checkout page (F5).
9. Scroll down to 'PostNL' shipping method.

**Expected result**
**The fee** (Fast delivery or Evening delivery) and **the extra service fee** (Do not deliver to neighbours) are clearly visible after the main shipping price (in the orange tab). Also **'Extra service' checkbox** remains checked.

**Actual result**
Only the main shipping price is visible (additional fee _evening or fast deliveries_ can be stayed sometimes, but any reload permanently losses it if performed again). 'Extra service' checkbox selection is lost.

**Workaround**
None

**Screenshots**

Before reload (when the selections have been just made):

![before-reload](https://github.com/user-attachments/assets/5697a2f6-81b9-4d46-8ccd-38e7ded4dcae)

After checkout page reload:

![after-reload](https://github.com/user-attachments/assets/b705c18b-49a9-46c4-a913-3008782b139b)

- Magento version (pure with only tig/postnl-magento2): 2.4.6
- PHP version: 8.1.3
- TIG PostNL version: 1.15.2

---

Also the same issue is reproducible on a highly customized Magento (with Swissup_Firecheckout and many custom modules):

- Magento version: 2.4.3-p3
- PHP version: 7.4.28
- TIG PostNL version: 1.15.2

**Comment by JorisPostNL** [comment]
Hi @YachYaroslav, thank you for reporting this issue.

Unfortunately the issue you mention is caused by the way the Magento2 framework itselfs handles the check-out data, and not by our plug-in. We have investigated this issue in the past and came to the conclusion we could not fix this issue without working on Magento2 itself rather than our plug-in. This means that unfortunately there is nothing we can do about this problem at this moment.

Note: since all three issues you posted concern the same root cause I will copy and paste this answer in all three tickets, so it's clear for other visitors what the outcome of your report was.

Kind regards
Joris - PostNL
